### ISSUE TITLE
publish schema as html via gh-pages

### ISSUE THREAD

**Issue by csae8092** [bundesverfassung-oesterreich/bv-schema-framework#14]
* don't check in .docx
* but if possible (and I think it is) create HTML from ODD  (bonus points for creating this via gh-actions) and publish this HTML via GH-Pages in this repo
* extra bonus points: integrate human readable documentation i.e. HTML into bv-static

**Comment by cfhaak** [comment]
going to use https://teigarage.tei-c.org/ege-webservice/#/ege-webservice/doGet
great service, documentation/ui completely useless

**Comment by cfhaak** [comment]
should add minimal css looks ******

**Comment by cfhaak** [comment]
moved this to https://github.com/bundesverfassung-oesterreich/bv-static/issues/25
